/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.rwtodd.pdfbmarks;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
	@Test void canParseName() {
		var pl = PageLabelParser.parseLine(" Name 21: Insert");
		assertEquals(new PageLabelParser.NamedPage(21, "Insert"), pl);
	}
	@Test void canParseArabicNumber() {
		var pl = PageLabelParser.parseLine("  \t  pAge 12 = booK   14  ");
		assertEquals(new PageLabelParser.NumberedPage(12, 14, "DecimalArabicNumerals"),pl);
	}
	@Test void canParseRomanNumber() {
		var pl = PageLabelParser.parseLine("  \t  pAge 2 = booK   140r");
		assertEquals(new PageLabelParser.NumberedPage(2, 140, "LowercaseRomanNumerals"),pl);
		pl = PageLabelParser.parseLine("  \t  pAge 202 = booK   1400R");
		assertEquals(new PageLabelParser.NumberedPage(202, 1400, "UppercaseRomanNumerals"),pl);
	}
}
